## **Migration Guide to Migrate from oasp4j-2.2.0 to oasp4j-2.4.0**

_io.oasp.module.jpa.dataaccess.api.AdvancedRevisionEntity.java_ is deprecated and has been moved to the package _io.oasp.module.jpa.dataaccess.base_.This deprecated class is provided for backward compatibility . So, if the user intends to use the deprecated class, he can do so by 

- pointing to (importing) the class _io.oasp.module.jpa.dataaccess.base.AdvancedRevisionEntity.java_ in all the classes where earlier , the class _io.oasp.module.jpa.dataaccess.api.AdvancedRevisionEntity.java_ was used.
- Modifying the schema definition of the table _RevInfo_  in ..\src\main\resources\db\migration\<dbName>\V0001__R001_Create_schema.sql, to use the column _user_ instead of _userLogin_' . Resulting schema definition follows : 


[source,sql]
--------
CREATE TABLE RevInfo(
  id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  timestamp BIGINT NOT NULL,
  user VARCHAR(255)
);
--------

- and doing a 'mvn clean install' of the project.